AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: websocket-chat

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 5
    Architectures:
      - x86_64

Resources:

  # ================= DYNAMODB =================
  ChatConnectionsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: groupId
          KeyType: HASH
        - AttributeName: connectionId
          KeyType: RANGE

  # ================= WEBSOCKET API =================
  ChatWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ChatWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  ChatWebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ChatWebSocketApi
      StageName: Prod
      AutoDeploy: true

  # ================= CONNECT =================
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/websocket/
      Handler: connect.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ChatConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatConnectionsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - connect.ts
        Target: es2020
        Minify: true

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $connect
      Target: !Sub integrations/${ConnectIntegration}

  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectFunction
      Principal: apigateway.amazonaws.com

  # ================= DEFAULT (CHAT) =================
  WebSocketDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/websocket/
      Handler: default.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ChatConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatConnectionsTable
        - Statement:
            - Effect: Allow
              Action: execute-api:ManageConnections
              Resource: "*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - default.ts
        Target: es2020
        Minify: true

  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDefaultFunction.Arn}/invocations

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $default
      Target: !Sub integrations/${DefaultIntegration}

  WebSocketDefaultPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDefaultFunction
      Principal: apigateway.amazonaws.com

  # ================= DISCONNECT =================
  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/websocket/
      Handler: disconnect.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ChatConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatConnectionsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - disconnect.ts
        Target: es2020
        Minify: true

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $disconnect
      Target: !Sub integrations/${DisconnectIntegration}

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectFunction
      Principal: apigateway.amazonaws.com

# ================= OUTPUT =================
Outputs:
  WebSocketEndpoint:
    Description: WebSocket API endpoint
    Value: !Sub "wss://${ChatWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
